### ISSUE TITLE
Incorporate 24-hr Storm Hydrographs

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/SC-RunoffModelingServices#62]
Resource: [SCDOT Spreadsheet SC Synthetic UH](https://doimspp.sharepoint.com/:x:/r/sites/SSPhaseII/Shared%20Documents/General/Planning/SC%20UH%20Method/SCDOT%20Spreadsheet_SC%20Synthetic%20UH_Verified%20on%205%20August%202022.xlsm?d=w9840a86621414c59884b8aa9e0ad817c&csf=1&web=1&e=MMPpTM)

- [ ] Include this table from the "WS & UH Data & Runoff Results" tab:
![image](https://user-images.githubusercontent.com/40237491/183969030-d8af4be9-ef3b-4e36-814f-11b50ef1379d.png)

- [ ] Include the "24-hr Storm Hydrographs" tab graphs and tables

**Comment by harper-wavra** [comment]
Table now be found in 24-hr Storm Hydrographs tab. 
https://doimspp-my.sharepoint.com/:x:/r/personal/kkolb_usgs_gov/_layouts/15/guestaccess.aspx?CID=b202ac48-fd6d-b4d6-cec4-dff77e1cc5bd&share=EetuQRkt-xtDjq-fHdhZd6wBCQaSyjGpVRadVBDnP8PHog

**Comment by harper-wavra** [comment]
I think I figured out what the 24-hour storm hydrograph tab is doing. It seems to just show the **24**-Hour Storm Hydrograph Ordinates graph and plots for each AEP on one page. For example, the values in the 10% column on the 24-hour storm hydrographs tab match the values in the 24-Hour Storm Hydrograph Ordinates column in the 10-yr D-hour storm hydrographs tab. 

This means we are calculating the values for the 10%, 4%, 2% and 1% columns, but not the 100%, 50% or 20% since we don't allow users to select 100, 50 or 20 as their AEP. This tab is basically displaying all the 24-hour plots on the same page, where we are just showing the single 24-hour plot that corresponds with the selected AEP.

**Comment by harper-wavra** [comment]
Closing in favor of https://github.com/USGS-WiM/StreamStats/issues/1547 and https://github.com/USGS-WiM/SC-RunoffModelingServices/issues/98.

We will give results for all AEP values - that way users can get the 24-hour results for each AEP.
